### ISSUE TITLE
Safezone Location Issue in Hawkland

### ISSUE THREAD

**Issue by Artistbma** [Linkupdated/LaCedule#99] opened 2015-05-02 02:41 UTC
People are apparently getting killed in the safezone at Hawkland and others are on the outside of the building yet still in safezone areas. I have not been given much information on the matter and have not been able to test much myself, but it should be looked into.

**Comment by Linkupdated** [comment] 2015-05-02 05:43
Duplicate of #61

**Closed as completed by Linkupdated** 2015-05-02 05:43 UTC
Labels: abuse fix, urgent, more testing required
